language: node_js
node_js:
  - "6"
before_script:
  - npm install gitbook-cli
  - npm install gitbook-publish@latest
script: 
  - gitpub
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  branch: gh-pages