language: node_js
node_js:
  - "6"
before_script:
  - npm install gitbook-cli
  - npm install gitbook-publish
script: 
  - gitpub
deploy:
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on: 
    branch: gh-pages
  target_branch: gh-pages