language: node_js
node_js:
  - "6"
before_install:
  - sudo apt-get install -y calibre
before_script:
  - npm install gitbook-cli
  - npm install gitbook-publish@latest
  - npm install ebook-convert
script: 
  - git config --global user.email "akshatamohanty@gmail.com"
  - git config --global user.name "Akshata"
  - gitbook pdf ./ ./published/urban-prototyping.pdf
  - git add ./published/urban-prototyping.pdf && git commit -m"Published PDF" 
  - git push "https://{USER_NAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}" master
  - gitpub
  - git branch
  - git remote -v
  - git push --force "https://{USER_NAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}" gh-pages 
